### ISSUE TITLE
File not found errors if userlang=en-gb

### ISSUE THREAD

**Issue by Jarry1250** [Krinkle/intuition-web#2] opened 2017-03-19 18:59 UTC
Contrast https://tools.wmflabs.org/jarry-common/?userlang=en-gb and https://tools.wmflabs.org/jarry-common/?userlang=en.

Example error: Warning: file_get_contents(/mnt/nfs/labstore-secondary-tools-project/intuition/src/Intuition/language/messages/general/en-gb.json): failed to open stream: No such file or directory in /mnt/nfs/labstore-secondary-tools-project/intuition/src/Intuition/src/Intuition.php on line 814

**Comment by Krinkle** [comment] 2017-06-11 00:54
Closing in favour of https://github.com/Krinkle/intuition/issues/81, this is not a bug with the preferences page at <https://tools.wmflabs.org/intuition/> but rather with the library. (Sorry about the two-repository confusion.)

**Closed by Krinkle** 2017-06-11 00:54 UTC
Labels: bug
